import { $DataInputStream, $DataOutputStream, $PrintWriter } from "@package/java/io";
import { $CtClass, $ClassPool } from "@package/javassist";
import { $List, $Map_, $Set } from "@package/java/util";
import { $Object } from "@package/java/lang";

declare module "@package/javassist/bytecode" {
    export class $ExceptionsAttribute extends $AttributeInfo {
        setExceptions(arg0: string[]): void;
        getExceptionIndexes(): number[];
        setExceptionIndexes(arg0: number[]): void;
        tableLength(): number;
        getException(arg0: number): number;
        getExceptions(): string[];
        static tag: string;
        constructor(arg0: $ConstPool);
    }
    export class $AttributeInfo {
        getConstPool(): $ConstPool;
        getName(): string;
        get(): number[];
        length(): number;
        set(arg0: number[]): void;
        copy(arg0: $ConstPool, arg1: $Map_<string, string>): $AttributeInfo;
        constructor(arg0: $ConstPool, arg1: string, arg2: number[]);
        get constPool(): $ConstPool;
        get name(): string;
    }
    export class $ClassFile {
        getRefClasses(arg0: $Map_<string, string>): void;
        setSuperclass(arg0: string): void;
        setInterfaces(arg0: string[]): void;
        getConstPool(): $ConstPool;
        setAccessFlags(arg0: number): void;
        renameClass(arg0: $Map_<string, string>): void;
        renameClass(arg0: string, arg1: string): void;
        getAccessFlags(): number;
        getInnerAccessFlags(): number;
        getStaticInitializer(): $MethodInfo;
        addField2(arg0: $FieldInfo): void;
        addMethod2(arg0: $MethodInfo): void;
        getSuperclassId(): number;
        setMajorVersion(arg0: number): void;
        setMinorVersion(arg0: number): void;
        setVersionToJava5(): void;
        addField(arg0: $FieldInfo): void;
        addAttribute(arg0: $AttributeInfo): void;
        getAttribute(arg0: string): $AttributeInfo;
        getMajorVersion(): number;
        getMinorVersion(): number;
        addMethod(arg0: $MethodInfo): void;
        removeAttribute(arg0: string): $AttributeInfo;
        getName(): string;
        isInterface(): boolean;
        getSuperclass(): string;
        getInterfaces(): string[];
        isFinal(): boolean;
        getMethod(arg0: string): $MethodInfo;
        getFields(): $List<$FieldInfo>;
        getMethods(): $List<$MethodInfo>;
        write(arg0: $DataOutputStream): void;
        setName(arg0: string): void;
        isAbstract(): boolean;
        getAttributes(): $List<$AttributeInfo>;
        compact(): void;
        prune(): void;
        addInterface(arg0: string): void;
        getSourceFile(): string;
        static JAVA_3: number;
        static JAVA_4: number;
        static JAVA_1: number;
        static JAVA_2: number;
        static MAJOR_VERSION: number;
        static JAVA_7: number;
        static JAVA_8: number;
        static JAVA_5: number;
        static JAVA_6: number;
        static JAVA_9: number;
        static JAVA_10: number;
        static JAVA_11: number;
        constructor(arg0: $DataInputStream);
        constructor(arg0: boolean, arg1: string, arg2: string);
        get constPool(): $ConstPool;
        get innerAccessFlags(): number;
        get staticInitializer(): $MethodInfo;
        get superclassId(): number;
        get interface(): boolean;
        get final(): boolean;
        get fields(): $List<$FieldInfo>;
        get methods(): $List<$MethodInfo>;
        get abstract(): boolean;
        get attributes(): $List<$AttributeInfo>;
        get sourceFile(): string;
    }
    export class $ConstPool {
        renameClass(arg0: $Map_<string, string>): void;
        renameClass(arg0: string, arg1: string): void;
        getThisClassInfo(): number;
        addClassInfo(arg0: $CtClass): number;
        addClassInfo(arg0: string): number;
        addUtf8Info(arg0: string): number;
        getUtf8Info(arg0: number): string;
        getFloatInfo(arg0: number): number;
        getIntegerInfo(arg0: number): number;
        getLongInfo(arg0: number): number;
        getDoubleInfo(arg0: number): number;
        addNameAndTypeInfo(arg0: string, arg1: string): number;
        addNameAndTypeInfo(arg0: number, arg1: number): number;
        addFieldrefInfo(arg0: number, arg1: number): number;
        addFieldrefInfo(arg0: number, arg1: string, arg2: string): number;
        addMethodrefInfo(arg0: number, arg1: number): number;
        addMethodrefInfo(arg0: number, arg1: string, arg2: string): number;
        addInterfaceMethodrefInfo(arg0: number, arg1: string, arg2: string): number;
        addInterfaceMethodrefInfo(arg0: number, arg1: number): number;
        getClassInfoByDescriptor(arg0: number): string;
        getNameAndTypeName(arg0: number): number;
        getNameAndTypeDescriptor(arg0: number): number;
        getMemberNameAndType(arg0: number): number;
        getFieldrefClass(arg0: number): number;
        getFieldrefClassName(arg0: number): string;
        getFieldrefNameAndType(arg0: number): number;
        getFieldrefName(arg0: number): string;
        getFieldrefType(arg0: number): string;
        getMethodrefClass(arg0: number): number;
        getMethodrefClassName(arg0: number): string;
        getMethodrefNameAndType(arg0: number): number;
        getMethodrefName(arg0: number): string;
        getMethodrefType(arg0: number): string;
        getInterfaceMethodrefClass(arg0: number): number;
        getInterfaceMethodrefClassName(arg0: number): string;
        getInterfaceMethodrefNameAndType(arg0: number): number;
        getInterfaceMethodrefName(arg0: number): string;
        getInterfaceMethodrefType(arg0: number): string;
        getLdcValue(arg0: number): $Object;
        getMethodHandleKind(arg0: number): number;
        getMethodHandleIndex(arg0: number): number;
        getInvokeDynamicBootstrap(arg0: number): number;
        getInvokeDynamicNameAndType(arg0: number): number;
        getInvokeDynamicType(arg0: number): string;
        getDynamicBootstrap(arg0: number): number;
        getDynamicNameAndType(arg0: number): number;
        getDynamicType(arg0: number): string;
        getModuleInfo(arg0: number): string;
        eqMember(arg0: string, arg1: string, arg2: number): string;
        addStringInfo(arg0: string): number;
        addIntegerInfo(arg0: number): number;
        addFloatInfo(arg0: number): number;
        addLongInfo(arg0: number): number;
        addDoubleInfo(arg0: number): number;
        addMethodHandleInfo(arg0: number, arg1: number): number;
        addMethodTypeInfo(arg0: number): number;
        addInvokeDynamicInfo(arg0: number, arg1: number): number;
        addDynamicInfo(arg0: number, arg1: number): number;
        addModuleInfo(arg0: number): number;
        addPackageInfo(arg0: number): number;
        getClassNames(): $Set<string>;
        isMember(arg0: string, arg1: string, arg2: number): number;
        getMethodTypeInfo(arg0: number): number;
        getMemberClass(arg0: number): number;
        getStringInfo(arg0: number): string;
        getPackageInfo(arg0: number): string;
        getTag(arg0: number): number;
        isConstructor(arg0: string, arg1: number): number;
        write(arg0: $DataOutputStream): void;
        print(): void;
        print(arg0: $PrintWriter): void;
        copy(arg0: number, arg1: $ConstPool, arg2: $Map_<string, string>): number;
        getSize(): number;
        getClassName(): string;
        getClassInfo(arg0: number): string;
        static CONST_String: number;
        static CONST_MethodType: number;
        static REF_newInvokeSpecial: number;
        static CONST_DynamicCallSite: number;
        static CONST_Methodref: number;
        static REF_putField: number;
        static CONST_Fieldref: number;
        static CONST_MethodHandle: number;
        static REF_getStatic: number;
        static REF_putStatic: number;
        static CONST_Float: number;
        static CONST_Long: number;
        static CONST_Package: number;
        static REF_invokeSpecial: number;
        static CONST_Utf8: number;
        static CONST_Dynamic: number;
        static REF_getField: number;
        static CONST_InterfaceMethodref: number;
        static REF_invokeVirtual: number;
        static CONST_Module: number;
        static CONST_Integer: number;
        static CONST_InvokeDynamic: number;
        static CONST_Class: number;
        static THIS: $CtClass;
        static CONST_Double: number;
        static REF_invokeStatic: number;
        static REF_invokeInterface: number;
        static CONST_NameAndType: number;
        constructor(arg0: $DataInputStream);
        constructor(arg0: string);
        get thisClassInfo(): number;
        get classNames(): $Set<string>;
        get size(): number;
        get className(): string;
    }
    export class $FieldInfo {
        getConstPool(): $ConstPool;
        setAccessFlags(arg0: number): void;
        getAccessFlags(): number;
        setDescriptor(arg0: string): void;
        getConstantValue(): number;
        addAttribute(arg0: $AttributeInfo): void;
        getAttribute(arg0: string): $AttributeInfo;
        removeAttribute(arg0: string): $AttributeInfo;
        getName(): string;
        getDescriptor(): string;
        setName(arg0: string): void;
        getAttributes(): $List<$AttributeInfo>;
        constructor(arg0: $ConstPool, arg1: string, arg2: string);
        get constPool(): $ConstPool;
        get constantValue(): number;
        get attributes(): $List<$AttributeInfo>;
    }
    export class $CodeAttribute extends $AttributeInfo implements $Opcode {
        getExceptionTable(): $ExceptionTable;
        getCodeLength(): number;
        insertLocalVar(arg0: number, arg1: number): void;
        getAttribute(arg0: string): $AttributeInfo;
        setAttribute(arg0: $StackMap): void;
        setAttribute(arg0: $StackMapTable): void;
        iterator(): $CodeIterator;
        getDeclaringClass(): string;
        getAttributes(): $List<$AttributeInfo>;
        getCode(): number[];
        getMaxLocals(): number;
        getMaxStack(): number;
        setMaxLocals(arg0: number): void;
        setMaxStack(arg0: number): void;
        computeMaxStack(): number;
        static tag: string;
        constructor(arg0: $ConstPool, arg1: number, arg2: number, arg3: number[], arg4: $ExceptionTable);
        get exceptionTable(): $ExceptionTable;
        get codeLength(): number;
        get declaringClass(): string;
        get attributes(): $List<$AttributeInfo>;
        get code(): number[];
    }
    export class $MethodInfo {
        setSuperclass(arg0: string): void;
        getConstPool(): $ConstPool;
        setAccessFlags(arg0: number): void;
        setCodeAttribute(arg0: $CodeAttribute): void;
        getCodeAttribute(): $CodeAttribute;
        getAccessFlags(): number;
        rebuildStackMapIf6(arg0: $ClassPool, arg1: $ClassFile): void;
        setDescriptor(arg0: string): void;
        getExceptionsAttribute(): $ExceptionsAttribute;
        removeExceptionsAttribute(): void;
        setExceptionsAttribute(arg0: $ExceptionsAttribute): void;
        removeCodeAttribute(): void;
        rebuildStackMap(arg0: $ClassPool): void;
        rebuildStackMapForME(arg0: $ClassPool): void;
        isStaticInitializer(): boolean;
        addAttribute(arg0: $AttributeInfo): void;
        getAttribute(arg0: string): $AttributeInfo;
        removeAttribute(arg0: string): $AttributeInfo;
        getName(): string;
        isMethod(): boolean;
        getDescriptor(): string;
        isConstructor(): boolean;
        setName(arg0: string): void;
        getAttributes(): $List<$AttributeInfo>;
        getLineNumber(arg0: number): number;
        static nameInit: string;
        static doPreverify: boolean;
        static nameClinit: string;
        constructor(arg0: $ConstPool, arg1: string, arg2: $MethodInfo, arg3: $Map_<string, string>);
        constructor(arg0: $ConstPool, arg1: string, arg2: string);
        set superclass(value: string);
        get constPool(): $ConstPool;
        get staticInitializer(): boolean;
        get method(): boolean;
        get constructor(): boolean;
        get attributes(): $List<$AttributeInfo>;
    }
}
