#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jul 26 12:25:35 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
