import { $Animation_ } from "@package/com/zigythebird/playeranimcore/animation";
import { $Vec3f } from "@package/com/zigythebird/playeranimcore/math";
import { $Pair } from "@package/it/unimi/dsi/fastutil";
import { $TransformType_ } from "@package/com/zigythebird/playeranimcore/enums";

declare module "@package/com/zigythebird/playeranimcore/bones" {
    export class $AdvancedPlayerAnimBone extends $PlayerAnimBone implements $IBoneEnabled {
        setRotXTransitionLength(rotXTransitionLength: number): void;
        setRotYTransitionLength(rotYTransitionLength: number): void;
        setRotZTransitionLength(rotZTransitionLength: number): void;
        setPositionXTransitionLength(positionXTransitionLength: number): void;
        setPositionYTransitionLength(positionYTransitionLength: number): void;
        setPositionZTransitionLength(positionZTransitionLength: number): void;
        setScaleXTransitionLength(scaleXTransitionLength: number): void;
        setScaleYTransitionLength(scaleYTransitionLength: number): void;
        setScaleZTransitionLength(scaleZTransitionLength: number): void;
        setBendTransitionLength(bendTransitionLength: number): void;
        isPositionXEnabled(): boolean;
        isPositionYEnabled(): boolean;
        isPositionZEnabled(): boolean;
        isRotXEnabled(): boolean;
        isRotYEnabled(): boolean;
        isRotZEnabled(): boolean;
        isScaleXEnabled(): boolean;
        isScaleYEnabled(): boolean;
        isScaleZEnabled(): boolean;
        setPositionEnabled(enabled: boolean): void;
        setRotEnabled(enabled: boolean): void;
        setScaleEnabled(enabled: boolean): void;
        isBendEnabled(): boolean;
        setEnabled(enabled: boolean): void;
        rotXEnabled: boolean;
        positionZTransitionLength: number;
        scaleZ: number;
        positionX: number;
        scaleX: number;
        positionY: number;
        scaleY: number;
        positionZ: number;
        rotXTransitionLength: number;
        rotX: number;
        rotZ: number;
        positionYTransitionLength: number;
        rotY: number;
        bend: number;
        scaleZTransitionLength: number;
        bendTransitionLength: number;
        positionYEnabled: boolean;
        positionZEnabled: boolean;
        scaleYTransitionLength: number;
        bendEnabled: boolean;
        rotYTransitionLength: number;
        scaleYEnabled: boolean;
        scaleXEnabled: boolean;
        scaleZEnabled: boolean;
        scaleXTransitionLength: number;
        positionXTransitionLength: number;
        positionXEnabled: boolean;
        rotZTransitionLength: number;
        rotYEnabled: boolean;
        rotZEnabled: boolean;
        constructor(name: string);
        set positionEnabled(value: boolean);
        set rotEnabled(value: boolean);
        set scaleEnabled(value: boolean);
        set enabled(value: boolean);
    }
    export class $PlayerAnimBone {
        saveSnapshot(): $BoneSnapshot;
        updateScale(scaleX: number, scaleY: number, scaleZ: number): void;
        getPositionVector(): $Vec3f;
        getScaleVector(): $Vec3f;
        addRotationOffsetFromBone(source: $PlayerAnimBone): void;
        setBend(value: number): void;
        copyOtherBone(bone: $PlayerAnimBone): $PlayerAnimBone;
        mulPos(value: number): $PlayerAnimBone;
        mulPos(x: number, y: number, z: number): $PlayerAnimBone;
        divPos(value: number): $PlayerAnimBone;
        divPos(x: number, y: number, z: number): $PlayerAnimBone;
        addRot(x: number, y: number, z: number): $PlayerAnimBone;
        addRot(value: number): $PlayerAnimBone;
        mulRot(x: number, y: number, z: number): $PlayerAnimBone;
        mulRot(value: number): $PlayerAnimBone;
        divRot(x: number, y: number, z: number): $PlayerAnimBone;
        divRot(value: number): $PlayerAnimBone;
        divScale(x: number, y: number, z: number): $PlayerAnimBone;
        divScale(value: number): $PlayerAnimBone;
        copySnapshot(snapshot: $BoneSnapshot): void;
        copySnapshotSafe(snapshot: $AdvancedBoneSnapshot): $PlayerAnimBone;
        mulScale(value: number): $PlayerAnimBone;
        mulScale(x: number, y: number, z: number): $PlayerAnimBone;
        beginOrEndTickLerp(bone: $AdvancedPlayerAnimBone, animTime: number, animation: $Animation_): $PlayerAnimBone;
        copyOtherBoneIfNotDisabled(bone: $PlayerAnimBone): $PlayerAnimBone;
        getScaleX(): number;
        getScaleY(): number;
        getScaleZ(): number;
        getPosZ(): number;
        setPosX(value: number): void;
        setPosY(value: number): void;
        addPos(x: number, y: number, z: number): $PlayerAnimBone;
        addPos(value: number): $PlayerAnimBone;
        setToInitialPose(): void;
        applyOtherBone(bone: $PlayerAnimBone): $PlayerAnimBone;
        updateRotation(xRot: number, yRot: number, zRot: number): void;
        getRotY(): number;
        setRotY(value: number): void;
        getRotX(): number;
        setRotX(value: number): void;
        addScale(x: number, y: number, z: number): $PlayerAnimBone;
        addScale(value: number): $PlayerAnimBone;
        getPosX(): number;
        getPosY(): number;
        getBend(): number;
        setPosZ(value: number): void;
        getRotZ(): number;
        setScaleX(value: number): void;
        setScaleY(value: number): void;
        setScaleZ(value: number): void;
        setRotZ(value: number): void;
        updatePosition(posX: number, posY: number, posZ: number): void;
        getName(): string;
        scale(value: number): $PlayerAnimBone;
        add(bone: $PlayerAnimBone): $PlayerAnimBone;
        getRotationVector(): $Vec3f;
        scaleX: number;
        positionY: number;
        scaleY: number;
        positionZ: number;
        rotX: number;
        rotZ: number;
        rotY: number;
        bend: number;
        scaleZ: number;
        positionX: number;
        constructor(name: string);
        get positionVector(): $Vec3f;
        get scaleVector(): $Vec3f;
        get name(): string;
        get rotationVector(): $Vec3f;
    }
    export class $IBoneEnabled {
    }
    export interface $IBoneEnabled {
        isPositionXEnabled(): boolean;
        isPositionYEnabled(): boolean;
        isPositionZEnabled(): boolean;
        isRotXEnabled(): boolean;
        isRotYEnabled(): boolean;
        isRotZEnabled(): boolean;
        isScaleXEnabled(): boolean;
        isScaleYEnabled(): boolean;
        isScaleZEnabled(): boolean;
        isBendEnabled(): boolean;
        get positionXEnabled(): boolean;
        get positionYEnabled(): boolean;
        get positionZEnabled(): boolean;
        get rotXEnabled(): boolean;
        get rotYEnabled(): boolean;
        get rotZEnabled(): boolean;
        get scaleXEnabled(): boolean;
        get scaleYEnabled(): boolean;
        get scaleZEnabled(): boolean;
        get bendEnabled(): boolean;
    }
    export class $AdvancedBoneSnapshot extends $BoneSnapshot {
        scaleYEnabled: boolean;
        positionYEnabled: boolean;
        positionZEnabled: boolean;
        rotXEnabled: boolean;
        scaleXEnabled: boolean;
        bendEnabled: boolean;
        scaleZEnabled: boolean;
        bone: $PlayerAnimBone;
        positionXEnabled: boolean;
        rotYEnabled: boolean;
        rotZEnabled: boolean;
        constructor(bone: $PlayerAnimBone);
    }
    export class $BoneSnapshot {
        updateScale(scaleX: number, scaleY: number, scaleZ: number): void;
        getOffsetZ(): number;
        updateOffset(offsetX: number, offsetY: number, offsetZ: number): void;
        getScaleX(): number;
        getScaleY(): number;
        getScaleZ(): number;
        setToInitialPose(): void;
        updateRotation(rotX: number, rotY: number, rotZ: number): void;
        getRotY(): number;
        getRotX(): number;
        getBend(): number;
        getRotZ(): number;
        getOffsetX(): number;
        getOffsetY(): number;
        getBone(): $PlayerAnimBone;
        getBendAxis(): number;
        updateBend(bendAxis: number, bend: number): void;
        updateBend(bend: $Pair<number, number>): void;
        getTransformFromType(type: $TransformType_): $Vec3f;
        bone: $PlayerAnimBone;
        constructor(bone: $PlayerAnimBone);
        constructor(bone: $BoneSnapshot);
        constructor(bone: $PlayerAnimBone, isInitial: boolean);
        constructor();
        get offsetZ(): number;
        get scaleX(): number;
        get scaleY(): number;
        get scaleZ(): number;
        get rotY(): number;
        get rotX(): number;
        get bend(): number;
        get rotZ(): number;
        get offsetX(): number;
        get offsetY(): number;
        get bendAxis(): number;
    }
}
