import { $Level_ } from "@package/net/minecraft/world/level";
import { $DefaultConstructorMarker } from "@package/kotlin/jvm/internal";
import { $TagKey } from "@package/net/minecraft/tags";
import { $ItemStack_, $ItemStack } from "@package/net/minecraft/world/item";
import { $Fluid } from "@package/net/minecraft/world/level/material";
import { $EntityDimensions, $EntityType_, $Entity$RemovalReason, $Pose, $PortalProcessor, $Entity } from "@package/net/minecraft/world/entity";
import { $FluidType } from "@package/net/neoforged/neoforge/fluids";
import { $UUID, $List, $Map, $List_ } from "@package/java/util";
import { $RandomSource } from "@package/net/minecraft/util";
import { $SynchedEntityData, $EntityDataAccessor } from "@package/net/minecraft/network/syncher";
import { $Object2DoubleMap } from "@package/it/unimi/dsi/fastutil/objects";
import { $BlockPos, $BlockPos_, $Direction } from "@package/net/minecraft/core";
import { $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $TreeType_, $TreeType } from "@package/dev/pandasystems/fallingtrees/api";
import { $AtomicInteger } from "@package/java/util/concurrent/atomic";
import { $Vec3 } from "@package/net/minecraft/world/phys";
import { $EntityInLevelCallback } from "@package/net/minecraft/world/level/entity";

declare module "@package/dev/pandasystems/fallingtrees/entity" {
    export class $TreeEntity$Companion {
        getBLOCKS(): $EntityDataAccessor<$Map<$BlockPos, $BlockState>>;
        getDROPS(): $EntityDataAccessor<$List<$ItemStack>>;
        getORIGIN_POS(): $EntityDataAccessor<$BlockPos>;
        getFALL_DIRECTION(): $EntityDataAccessor<$Direction>;
        getTREE_TYPE_LOCATION(): $EntityDataAccessor<string>;
        constructor($constructor_marker: $DefaultConstructorMarker);
        get BLOCKS(): $EntityDataAccessor<$Map<$BlockPos, $BlockState>>;
        get DROPS(): $EntityDataAccessor<$List<$ItemStack>>;
        get ORIGIN_POS(): $EntityDataAccessor<$BlockPos>;
        get FALL_DIRECTION(): $EntityDataAccessor<$Direction>;
        get TREE_TYPE_LOCATION(): $EntityDataAccessor<string>;
    }
    export class $TreeEntity extends $Entity {
        setTreeType(arg0: $TreeType_): void;
        getMaxLifeTimeTick(): number;
        static access$getFALL_DIRECTION$cp(): $EntityDataAccessor<any>;
        static access$getBLOCKS$cp(): $EntityDataAccessor<any>;
        static access$getDROPS$cp(): $EntityDataAccessor<any>;
        static access$getORIGIN_POS$cp(): $EntityDataAccessor<any>;
        static access$getTREE_TYPE_LOCATION$cp(): $EntityDataAccessor<any>;
        getLifetime(partialTick: number): number;
        getTreeType(): $TreeType;
        getOriginPos(): $BlockPos;
        setOwner(arg0: $Entity): void;
        setData(owner: $Entity, tree: $TreeType_, originBlock: $BlockPos_, blockPosList: $List_<$BlockPos_>, drops: $List_<$ItemStack_>): void;
        getOwner(): $Entity;
        getBlocks(): $Map<$BlockPos, $BlockState>;
        firstTick: boolean;
        wasEyeInWater: boolean;
        hasImpulse: boolean;
        static ENTITY_COUNTER: $AtomicInteger;
        uuid: $UUID;
        stuckSpeedMultiplier: $Vec3;
        tickCount: number;
        noPhysics: boolean;
        yo: number;
        static FLAG_ONFIRE: number;
        static BOARDING_COOLDOWN: number;
        removalReason: $Entity$RemovalReason;
        yRotO: number;
        static CONTENTS_SLOT_INDEX: number;
        yRot: number;
        moveDist: number;
        static ID_TAG: string;
        mainSupportingBlockPos: ($BlockPos) | undefined;
        static FLAG_FALL_FLYING: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_1_0: number;
        xRotO: number;
        boardingCooldown: number;
        zo: number;
        static DATA_POSE: $EntityDataAccessor<$Pose>;
        walkDist: number;
        xOld: number;
        noCulling: boolean;
        wasInPowderSnow: boolean;
        hurtMarked: boolean;
        entityData: $SynchedEntityData;
        forgeFluidTypeHeight: $Object2DoubleMap<$FluidType>;
        invulnerableTime: number;
        static UUID_TAG: string;
        static BASE_TICKS_REQUIRED_TO_FREEZE: number;
        fallDistance: number;
        portalProcess: $PortalProcessor;
        verticalCollision: boolean;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_5: number;
        static MAX_ENTITY_TAG_COUNT: number;
        static DELTA_AFFECTED_BY_BLOCKS_BELOW_0_2: number;
        verticalCollisionBelow: boolean;
        static Companion: $TreeEntity$Companion;
        random: $RandomSource;
        yOld: number;
        static DEFAULT_BB_WIDTH: number;
        /**
         * @deprecated
         */
        fluidHeight: $Object2DoubleMap<$TagKey<$Fluid>>;
        eyeHeight: number;
        minorHorizontalCollision: boolean;
        static DEFAULT_BB_HEIGHT: number;
        levelCallback: $EntityInLevelCallback;
        owner: $Entity;
        treeType: $TreeType;
        walkDistO: number;
        static FREEZE_HURT_FREQUENCY: number;
        flyDist: number;
        isInPowderSnow: boolean;
        static ATTACHMENTS_NBT_KEY: string;
        static PASSENGERS_TAG: string;
        blocksBuilding: boolean;
        stringUUID: string;
        wasOnFire: boolean;
        zOld: number;
        static TOTAL_AIR_SUPPLY: number;
        xo: number;
        static FLAG_GLOWING: number;
        static DATA_SHARED_FLAGS_ID: $EntityDataAccessor<number>;
        static BASE_SAFE_FALL_DISTANCE: number;
        wasTouchingWater: boolean;
        horizontalCollision: boolean;
        dimensions: $EntityDimensions;
        constructor(entityType: $EntityType_<never>, level: $Level_);
        get maxLifeTimeTick(): number;
        get originPos(): $BlockPos;
        get blocks(): $Map<$BlockPos, $BlockState>;
    }
}
