import { $File_, $File } from "@package/java/io";
import { $MapDimension } from "@package/xaero/map/world";
import { $CompoundTag_ } from "@package/net/minecraft/nbt";
import { $Fluid_ } from "@package/net/minecraft/world/level/material";
import { $MapRegion, $OverlayManager, $LeveledRegion, $BranchLeveledRegion } from "@package/xaero/map/region";
import { $Biome_ } from "@package/net/minecraft/world/level/biome";
import { $ImmutableMap } from "@package/com/google/common/collect";
import { $BiomeGetter } from "@package/xaero/map/biome";
import { $ArrayList } from "@package/java/util";
import { $Consumer_ } from "@package/java/util/function";
import { $Registry, $HolderLookup } from "@package/net/minecraft/core";
import { $ILinkedChainNode } from "@package/xaero/map/util/linked";
import { $Path_, $Path } from "@package/java/nio/file";
import { $BlockState } from "@package/net/minecraft/world/level/block/state";
import { $MapProcessor } from "@package/xaero/map";
import { $Block_ } from "@package/net/minecraft/world/level/block";
import { $MapTileSelection, $ExportScreen } from "@package/xaero/map/gui";
import { $PNGExporter } from "@package/xaero/map/file/export";
import { $BlockStateShortShapeCache } from "@package/xaero/map/cache";
export * as worldsave from "@package/xaero/map/file/worldsave";
export * as export from "@package/xaero/map/file/export";

declare module "@package/xaero/map/file" {
    export class $MapRegionInfo {
    }
    export interface $MapRegionInfo {
        getCacheFile(): $File;
        hasLookedForCache(): boolean;
        setShouldCache(arg0: boolean, arg1: string): void;
        setCacheFile(arg0: $File_): void;
        getRegionFile(): $File;
        getWorldId(): string;
        getMwId(): string;
        getRegionX(): number;
        getRegionZ(): number;
        getDimId(): string;
        shouldCache(): boolean;
        get regionFile(): $File;
        get worldId(): string;
        get mwId(): string;
        get regionX(): number;
        get regionZ(): number;
        get dimId(): string;
    }
    export class $RegionDetection implements $MapRegionInfo, $ILinkedChainNode<$RegionDetection> {
        isHasHadTerrain(): boolean;
        getCacheFile(): $File;
        hasLookedForCache(): boolean;
        setShouldCache(arg0: boolean, arg1: string): void;
        setCacheFile(arg0: $File_): void;
        getRegionFile(): $File;
        getWorldId(): string;
        getMwId(): string;
        transferInfoFrom(arg0: $MapRegion): void;
        getInitialVersion(): number;
        transferInfoTo(arg0: $MapRegion): void;
        transferInfoPostAddTo(arg0: $MapRegion, arg1: $MapProcessor): void;
        onDestroyed(): void;
        getRegionX(): number;
        getRegionZ(): number;
        getDimId(): string;
        shouldCache(): boolean;
        getNext(): $RegionDetection;
        isDestroyed(): boolean;
        getPrevious(): $RegionDetection;
        isRemoved(): boolean;
        setNext(arg0: $RegionDetection): void;
        setRemoved(arg0: boolean): void;
        setPrevious(arg0: $RegionDetection): void;
        constructor(arg0: string, arg1: string, arg2: string, arg3: number, arg4: number, arg5: $File_, arg6: number, arg7: boolean);
        get hasHadTerrain(): boolean;
        get regionFile(): $File;
        get worldId(): string;
        get mwId(): string;
        get initialVersion(): number;
        get regionX(): number;
        get regionZ(): number;
        get dimId(): string;
        get destroyed(): boolean;
    }
    export class $MapSaveLoad {
        backupFile(arg0: $File_, arg1: number): void;
        getMainFolder(arg0: string, arg1: string): $Path;
        getMWSubFolder(arg0: string, arg1: string, arg2: string): $Path;
        getCacheFile(arg0: $MapRegionInfo, arg1: number, arg2: boolean, arg3: boolean): $File;
        removeToCache(arg0: $LeveledRegion<never>): void;
        removeToCache(arg0: $MapDimension, arg1: number): $LeveledRegion<never>;
        toCacheContains(arg0: $LeveledRegion<never>): boolean;
        saveExists(arg0: $MapRegion): boolean;
        removeToLoad(arg0: $MapRegion): void;
        removeTempCacheRequest(arg0: $File_): boolean;
        addTempCacheRequest(arg0: $File_): void;
        getCaveLayerFolder(arg0: number, arg1: $Path_): $Path;
        getNormalFile(arg0: $MapRegion): $File;
        detectRegionsFromFiles(arg0: $MapDimension, arg1: string, arg2: string, arg3: string, arg4: $Path_, arg5: string, arg6: number, arg7: number, arg8: number, arg9: number, arg10: $Consumer_<$RegionDetection>): void;
        detectRegions(arg0: number): void;
        getTempFile(arg0: $File_): $File;
        loadRegion(arg0: $MapRegion, arg1: $HolderLookup<$Block_>, arg2: $Registry<$Block_>, arg3: $Registry<$Fluid_>, arg4: $BiomeGetter, arg5: boolean, arg6: number): boolean;
        addToLoad(arg0: $MapRegion, arg1: string, arg2: boolean): void;
        beingSaved(arg0: $MapDimension, arg1: number, arg2: number): boolean;
        exportPNG(arg0: $ExportScreen, arg1: $MapTileSelection): boolean;
        requestCache(arg0: $LeveledRegion<never>): void;
        getOldFolder(arg0: string, arg1: string): $Path;
        clearToLoad(): void;
        updateSave(arg0: $LeveledRegion<never>, arg1: number, arg2: number): void;
        setRegionDetectionComplete(arg0: boolean): void;
        getOldFormatSupport(): $OldFormatSupport;
        setMapProcessor(arg0: $MapProcessor): void;
        isRegionDetectionComplete(): boolean;
        getSizeOfToLoad(): number;
        getToSave(): $ArrayList<$MapRegion>;
        getSizeOfToLoadBranchCache(): number;
        getNextToLoadByViewing(): $LeveledRegion<never>;
        requestBranchCache(arg0: $BranchLeveledRegion, arg1: string, arg2: boolean): void;
        requestBranchCache(arg0: $BranchLeveledRegion, arg1: string): void;
        setNextToLoadByViewing(arg0: $LeveledRegion<never>): void;
        requestLoad(arg0: $MapRegion, arg1: string, arg2: boolean): void;
        requestLoad(arg0: $MapRegion, arg1: string): void;
        safeMoveAndReplace(arg0: $Path_, arg1: $Path_, arg2: string, arg3: string): void;
        static getRootFolder(arg0: string): $Path;
        run(arg0: $HolderLookup<$Block_>, arg1: $Registry<$Block_>, arg2: $Registry<$Fluid_>, arg3: $BiomeGetter, arg4: $Registry<$Biome_>): void;
        getFile(arg0: $MapRegion): $File;
        safeDelete(arg0: $Path_, arg1: string): void;
        static currentCacheSaveMinorVersion: number;
        saveAll: boolean;
        static currentCacheSaveMajorVersion: number;
        loadingFiles: boolean;
        static SAVE_TIME: number;
        mainTextureLevel: number;
        constructor(arg0: $OverlayManager, arg1: $PNGExporter, arg2: $OldFormatSupport, arg3: $BlockStateShortShapeCache);
        get oldFormatSupport(): $OldFormatSupport;
        set mapProcessor(value: $MapProcessor);
        get sizeOfToLoad(): number;
        get toSave(): $ArrayList<$MapRegion>;
        get sizeOfToLoadBranchCache(): number;
    }
    export class $OldFormatSupport {
        fixBlock(arg0: $CompoundTag_, arg1: number): void;
        loadVanillaStates(): void;
        getStateForId(arg0: number): $BlockState;
        fixBiome(arg0: string, arg1: number): string;
        fixBiome(arg0: number, arg1: number): string;
        fixBiome(arg0: number, arg1: number, arg2: string): string;
        loadModdedStates(arg0: $MapProcessor, arg1: string, arg2: string, arg3: string): void;
        loadStates(): void;
        cc2BiomeRenames: $ImmutableMap<string, string>;
        constructor();
    }
}
